### ISSUE TITLE
REST Call Using Resty

### ISSUE THREAD

**Issue by dhiemaz** [iwanjunaid/basesvc#23]

**Comment by ilmimris** [comment]
mas @iwanjunaid ini maksudnya untuk apa ya?

**Comment by iwanjunaid** [comment]
@ilmimris Untuk komunikasi antar service tp lewat HTTP mas. Atau lebih enaknya kita diskusikan di daily meeting aja ya

**Comment by ilmimris** [comment]
> @ilmimris Untuk komunikasi antar service tp lewat HTTP mas. Atau lebih enaknya kita diskusikan di daily meeting aja ya

Oke boleh mas
