### ISSUE TITLE
Error Management

### ISSUE THREAD

**Issue by ilmimris** [iwanjunaid/basesvc#8]
PR https://github.com/iwanjunaid/sharedlib/pull/1

Assigned to:

Dimas
Ilmi

**Comment by ilmimris** [comment]
Error Management ini mau dibuat jadi satu package sendiri (beda repo) atau jadi satu dengan repo setiap service (ie. basesvc repo)?

Pertimbangan untuk jadi satu package sendiri adalah error code dan error message lebih mudah di-maintain karena sifatnya central, semua service mengacu ke satu package error management yang sama.

Bagaimana menurut rekan-rekan sekalian? @wibiaris @iwanjunaid @dhiemaz

**Comment by dhiemaz** [comment]
Tadi udah didiskusikan (pairing) sama Ilmi, poin tersebut masuk kedalam diskusi tadi : 
1. Bikin library beda repo
    pros
    a. Distribusi dan managementnya lebih mudah
    b. Membuat codebase basesvc lebih ringan

    cons
    a. Ketika ada update (penambahan) error code, maka perlu dipush juga repo tersebut.

2. Internal package
     pros
     a. Lebih mudah secara flow development karena cukup direpo itu aja yang dipush.
     cons
     a. Perlu effort komunikasi dengan engineer lain, karena distribusi error codenya ga merata, contoh : service A bikin error code 201 (error db connection), di service B bikin error code 201 (error validation), ini terjadi karena engineer service A dan service B ga "ngobrol" dulu sebelumnya. 

Kalo dari gw sih lebih prefer bikin library, tapi tadi gw sama Ilmi sudah diskusi untuk ngedistribusiin task yang tersisa (task gw sama Ilmi). Jadi kesepakatannya untuk error management akan ditackle sama Ilmi, gw akan fokus ke 2 task yaitu : 
1. Logger dan config (penyesuaian yang diinfokan digrup).
2. Graceful shutdown (karena feature ini belum kemerge di PR sebelumnya). 
3. Config hot reload (kasusnya sama dengan poin 2.)
4. Redis cache (minimum effort.)

**Comment by dhiemaz** [comment]
Catatan, untuk error codenya kita akan set sesuai dengan case author dan book dulu, untuk error code lainya, silahkan ditambahkan.

Untuk detailnya diinfokan sama Ilmi ya.

**Comment by iwanjunaid** [comment]
@ilmimris iya mas satu repo aja

**Comment by ilmimris** [comment]
> @ilmimris iya mas satu repo aja

mau dibuat di reponya mas @iwanjunaid atau di saya nih?
